# Generated by Django 6.0.4 on 2026-06-06 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['is_scanned'], name='qr_is_scanned_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['size', 'is_scanned'], name='qr_size_scanned_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['qr_data'], name='qr_data_idx'),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['status'], name='scan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['scanned_at'], name='scan_at_idx'),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['qr_code', 'status'], name='scan_qr_status_idx'),
        ),
    ]
